from django.urls import path
from .views import (
    ServerListDetailsAPI,
    LoRaDetailsAPI,
    SiteDetailsAPI,
    SearchMapViewAPI,
    SearchZoneViewAPI,
    CustomPowerSaveAndConsumeAPIView,
    CustomizeDeviceDetailsAPIView,
    CustomizeComplaintDetailsAPIView,
    ComplaintAndMaintenanceAPIView,
    PowerTrendAnalysisAPIView,GetZoneName,
    AppReportAPI,MonthlyDashboardDataDetailsAPIView,
    device_uplink,
    ZoneAPI,
    WardAPI,
    downlink_commands,
    SearchDeviseAPIView,
    RegistartionAPIView,
    MaintenanceAPIView,
    loginAPI,
    DeviceDetailsAPIView,
    DashboardDataDetailsAPIView,
    UpdateDeviceAPIView,
    DeviceRegisterAPIView,
    Savecount,
    LogoutAPIView,
    ComplaintAPIView,
    SupportAPI
    )
from django.contrib.auth import views as auth_views
from . import views
app_name = "users"
urlpatterns = [
    path('registartion/',RegistartionAPIView.as_view()),
    path('login/',loginAPI.as_view()),
    path('logout/',LogoutAPIView.as_view()),
    path('password_reset/',auth_views.PasswordResetView.as_view()),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view()),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view()),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view()),
    path('deviceregister/',DeviceRegisterAPIView.as_view()),
    path('getzonename/<str:zonename>/',GetZoneName.as_view()),
    path('zoneregister/',ZoneAPI.as_view()),
    path('wardregister/',WardAPI.as_view()),
    path('searchdeviseresult/<str:deveui>/',SearchDeviseAPIView.as_view()),
    path('devicebulkregister/',views.bulk_csv,name="bulk"),
    path('complaint/',ComplaintAPIView.as_view()),
    path('maintenance/',MaintenanceAPIView.as_view()), 
    path('devicedetails/',DeviceDetailsAPIView.as_view()),
    path('customdevicedetails/<str:sdate>/<str:edate>/',CustomizeDeviceDetailsAPIView.as_view()),
    path('dashboarddatadetails/',DashboardDataDetailsAPIView.as_view()),
    path('custompowersaveandconsume/<str:sdate>/<str:edate>/',CustomPowerSaveAndConsumeAPIView.as_view()),
    path('monthlydashboarddata/<str:month>/',MonthlyDashboardDataDetailsAPIView.as_view()),
    path('powertrendanalysis/<str:trendtype>/',PowerTrendAnalysisAPIView.as_view()),
    path('complaint_and_maintenance/',ComplaintAndMaintenanceAPIView.as_view()),
    path('customizecomplaintDetails/<str:sdate>/<str:edate>/',CustomizeComplaintDetailsAPIView.as_view()),
    path('zoneview/<str:zonetype>/',SearchZoneViewAPI.as_view()),
    path('mapview/<str:zonetype>/<str:wardname>/',SearchMapViewAPI.as_view()),
    path('powersave/',Savecount.as_view()),
    path('appreportdata/',AppReportAPI.as_view()),
    path('updatedevicedetails/<deveui>/', UpdateDeviceAPIView.as_view()),
    path('device_uplink/',views.device_uplink, name='uplink'),
    path('device_uplinkv4/',views.device_uplinkv4,name='device_uplinkv4'),
    path('payload_manager/',views.payload_manager,name='payload_manager'),
    path('payload_managerv4/',views.payload_managerv4,name='payload_managerv4'),
    path('downlinkcommands/<str:command>/<str:devEUI>/',views.set_command,name='downlink-commands'),
    path('setstatus_command/<str:command>/<str:devEUI>/<str:ctype>/',views.setstatus_command,name='setstatus_command'),
    path('set_schedule_command/',views.set_schedule_command,name='set_schedule_command'),
    path('payloaddata_power/',views.payloaddata_power,name='payloaddata_power'),
    path('loradetails/',LoRaDetailsAPI.as_view(),name='LoRaDetailsAPI'),
    path('sitedetails/',SiteDetailsAPI.as_view(),name='SiteDetailsAPI'),
    path('serverlistdetails/<str:sitename>/',ServerListDetailsAPI.as_view()),
    path('support/',SupportAPI.as_view()), 
]
 