# Generated by Django 4.2.5 on 2023-09-12 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='payloaddatav4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devEUI', models.CharField(default='None', max_length=100)),
                ('dev_status', models.CharField(default='None', max_length=20)),
                ('luc_detail', models.CharField(default='None', max_length=50)),
                ('schedule_mode', models.CharField(default='None', max_length=50)),
                ('relay_status', models.CharField(default='None', max_length=100)),
                ('power_grid_fail', models.CharField(default='None', max_length=100)),
                ('lamp_fali', models.CharField(default='None', max_length=100)),
                ('command_action_status', models.CharField(default='None', max_length=100)),
                ('time_stamp', models.DateTimeField(default='None')),
                ('sch_start_time', models.TimeField(default='None')),
                ('sch_end_time', models.TimeField(default='None')),
                ('default_dimming', models.IntegerField(default='None')),
                ('first_slot_time', models.TimeField(default='None')),
                ('first_slot_dimming', models.IntegerField(default='None')),
                ('second_slot_time', models.TimeField(default='None')),
                ('second_slot_dimming', models.IntegerField(default='None')),
                ('third_slot_time', models.TimeField(default='None')),
                ('third_slot_dimming', models.IntegerField(default='None')),
                ('fourth_slot_time', models.TimeField(default='None')),
                ('fourth_slot_dimming', models.IntegerField(default='None')),
                ('meter_data_interval', models.IntegerField(default='None')),
                ('current_dimming', models.FloatField(default='None')),
                ('meter_kwh', models.FloatField(default='None')),
                ('meter_voltage', models.FloatField(default='None')),
                ('meter_current', models.FloatField(default='None')),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device_register_details')),
            ],
        ),
    ]
