# Generated by Django 4.2.5 on 2023-09-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_payloaddatav4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payloaddatav4',
            name='device',
        ),
    ]
