# Generated by Django 4.2 on 2023-09-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_payloaddatav4_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payloaddata',
            name='command_action_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payloaddata',
            name='current_dimming',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payloaddata',
            name='default_dimming',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payloaddata',
            name='dev_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payloaddata',
            name='first_slot_dimming',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payloaddata',
            name='first_slot_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payloaddata',
            name='fourth_slot_dimming',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payloaddata',
            name='fourth_slot_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payloaddata',
            name='lamp_fali',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payloaddata',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payloaddata',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payloaddata',
            name='luc_detail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payloaddata',
            name='meter_current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payloaddata',
            name='meter_data_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payloaddata',
            name='meter_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payloaddata',
            name='meter_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payloaddata',
            name='power_grid_fail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payloaddata',
            name='relay_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payloaddata',
            name='sch_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payloaddata',
            name='sch_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payloaddata',
            name='schedule_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payloaddata',
            name='second_slot_dimming',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payloaddata',
            name='second_slot_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payloaddata',
            name='third_slot_dimming',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payloaddata',
            name='third_slot_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payloaddata',
            name='time_stamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
