# Generated by Django 4.2.5 on 2023-09-29 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_payload_power_mst_power_save_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoRaServerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=50)),
                ('lora_version', models.CharField(max_length=50)),
                ('user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('lora_key', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='site_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('multicast_id', models.CharField(max_length=50)),
                ('fk_server_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loraserverdetails')),
            ],
        ),
    ]
