# Generated by Django 4.2.5 on 2023-09-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_loraserverdetails_site_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_manager',
            name='site_owner',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
