# Generated by Django 4.2.5 on 2023-10-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_site_manager_server_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_register_details',
            name='multicast_add',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device_register_details',
            name='server_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device_register_details',
            name='site_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
