# Generated by Django 4.2.5 on 2023-10-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_device_register_details_multicast_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_manager',
            name='site_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
