# Generated by Django 4.2.5 on 2023-10-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_support_mst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support_mst',
            name='requester_number',
            field=models.CharField(max_length=15),
        ),
    ]
