# Generated by Django 4.2.5 on 2023-10-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_support_mst_requester_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uplinkdata',
            name='payload',
            field=models.CharField(max_length=255),
        ),
    ]
