# Generated by Django 4.2.5 on 2023-12-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_uplinkdata_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_register_details',
            name='device_cat',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
