# Generated by Django 4.2.5 on 2023-12-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_device_register_details_device_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device_register_details',
            old_name='device_cat',
            new_name='device_category',
        ),
    ]
